
import jsPDF from 'jspdf';
import { getServiceRequirements } from './poojaRequirements';

export const generatePujaRequirementsPDF = (serviceKey: string, customerName: string, date: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  let yPosition = 20;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(139, 69, 19); // Maroon color
  doc.text('Telugu Pandit Services', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Puja Requirements & Guidelines', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 20;

  // Customer and service details
  const requirements = getServiceRequirements(serviceKey);
  doc.setFontSize(12);
  doc.setTextColor(139, 69, 19);
  doc.text(`Service: ${requirements.title}`, 20, yPosition);
  yPosition += 8;
  doc.text(`Customer: ${customerName}`, 20, yPosition);
  yPosition += 8;
  doc.text(`Date: ${date}`, 20, yPosition);
  yPosition += 20;

  // Requirements title
  doc.setFontSize(14);
  doc.setTextColor(139, 69, 19);
  doc.text('Items to Bring:', 20, yPosition);
  yPosition += 15;

  // Requirements list
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  
  requirements.items.forEach((item, index) => {
    if (yPosition > pageHeight - 30) {
      doc.addPage();
      yPosition = 20;
    }
    
    doc.text(`• ${item}`, 25, yPosition);
    yPosition += 6;
  });

  yPosition += 15;

  // Important notes section
  if (yPosition > pageHeight - 60) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(12);
  doc.setTextColor(139, 69, 19);
  doc.text('Important Notes:', 20, yPosition);
  yPosition += 10;

  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);
  
  const notes = [
    '• Please ensure all items are clean and fresh',
    '• Arrive 15-20 minutes before the scheduled time',
    '• If you want anything to be customized according to your cultural',
    '  needs, please let our priest know beforehand',
    '• These requirements are general guidelines for everyone',
    '• Our priest will guide you through the entire ceremony',
    '• Feel free to contact us if you have any questions'
  ];

  notes.forEach(note => {
    if (yPosition > pageHeight - 20) {
      doc.addPage();
      yPosition = 20;
    }
    doc.text(note, 20, yPosition);
    yPosition += 7;
  });

  // Footer
  yPosition = pageHeight - 30;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Telugu Pandit Services', pageWidth / 2, yPosition, { align: 'center' });
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition + 5, { align: 'center' });

  // Download the PDF
  doc.save(`${requirements.title.replace(/\s+/g, '-')}-Requirements.pdf`);
};
